giphy_api_key: API_KEY_HERE
tenor_api_key: API_KEY_HERE
# Source of the gifs, can be either giphy or tenor
provider: tenor
# Uncomment desired source for random gifs on giphy
# can be either trending or random
# note: this is only used when no query is passed!
source: trending
# desired response type:
#   message: regular message containing url to gif
#   reply: reply-message containing url to gif
#   upload: image upload to the room
response_type: message
